name: voxtube
description: Traduction vidéo en temps réel multi-plateforme
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2

  # UI & Navigation
  cupertino_icons: ^1.0.6
  google_fonts: ^7.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Network
  http: ^1.2.0
  web_socket_channel: ^3.0.3
  google_mobile_ads: ^5.0.0
  # YouTube
  youtube_player_flutter: ^9.0.0
  youtube_explode_dart: ^3.0.5  # Pour recherche YouTube
  
  # Audio
  audio_session: ^0.2.2
  audioplayers: ^6.5.1    # ✅ ALTERNATIVE
  just_audio: ^0.10.5
  path_provider: ^2.1.0

  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # WebView
  webview_flutter: ^4.4.4

  file_picker: ^10.3.8
  path: ^1.9.0
  video_player: ^2.8.0  # ✅ NOUVEAU
  image_picker: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/voxtube_logo.png

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

